### PR TITLE
OU-509: Style Material UI <Chip> component like PatternFly <Label> component

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
[OU-509](https://issues.redhat.com//browse/OU-509): Style Material UI <Chip> component like PatternFly <Label> component

## Screenshots
image

### CODE REVIEW

**Comment by jgbernalp** [comment]
cc @fkargbo

**Comment by andreasgerstmayr** [comment]
note: the colors will change once #53 is merged

**Comment by andreasgerstmayr** [comment]
> note: the colors will change once #53 is merged

#53 was merged, I've updated the screenshot (and resolved the merge conflicts)

**Pull request merged**
